### ISSUE TITLE
compilation problem  ether wallet v0.9.1

### ISSUE THREAD

**Issue by nazimran** [Giveth/fund-forwarder#2]
MiniMeToken.sol
error output:
Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.
               Checkpoint newCheckPoint = checkpoints[ checkpoints.length++ ];
               ^----------------------^

**Comment by Quazia** [comment]
I believe this is just a warning. If you'd like to give me some more information I can try and help but otherwise I'm going to close this issue. Also, keep in mind the master branch was outdated at the time of this issue as the contracts have been updated to use the new common contracts.
